axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    servers: localhost

datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:6432/master
  username: postgres
  password: changeit

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate

solver:
  url: http://172.17.0.4:7000/replenish

server:
  port: 9456