axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  axonserver:
    servers: 172.22.0.4

datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://172.22.0.5:5432/master
  username: postgres
  password: changeit

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate



solver:
  url: http://172.22.0.6:7000/replenish

ad:
  rules:
    - "#event matches 'UserEnteredBeaconProximityEvent' && #storeId matches 'STORE00001' && #skuId matches 'SKU0000001' && #amountSpent > 500 ? 10 : null"
    - "#event matches 'UserHomeSkuQuantityEvent' && #deviceId matches 'COOLER0001' && #skuId matches 'SKU0000001' && #homeSkuQuantity < 200 && #amountSpent > 1000 ? 15 : null"

server:
  port: 9456